"""Sub-agent 5: implementer.

Edits dbt models / macros / yml per the validated requirements. Implementing
SQL changes correctly requires an LLM in the loop, so this module emits a
structured change plan + LLM prompt; the supervisor either delegates to
Cursor's coding agent or surfaces the prompt for the user to drive.

The module also prepares the branch metadata (name, base, prefix) so the
pr-author sub-agent can pick up from a known starting point.
"""

from __future__ import annotations

import re
import subprocess
from pathlib import Path

from agents.arr_quarter_close.contracts import (
    FileEdit,
    ImplementationInput,
    ImplementationResult,
    RoleResult,
    RoleStatus,
    resolve_default_llm_model,
)
from agents.arr_quarter_close.lessons import (
    format_lessons_for_prompt,
    get_cached_recorder,
)

ROLE = "implementer"


def _lessons_block(role: str, max_lessons: int = 8) -> str:
    recorder = get_cached_recorder()
    if recorder is None:
        return ""
    return format_lessons_for_prompt(
        recorder.load_for(role, max_lessons=max_lessons),
        heading="Lessons learned from prior runs",
    )


def plan(req: ImplementationInput) -> dict:
    branch = _branch_name(req)
    return {
        "role": ROLE,
        "branch": branch,
        "base_branch": "qa",
        "affected_models": req.validation.code.affected_models,
        "affected_macros": req.validation.code.affected_macros,
        "approach": (
            "1) git checkout -b <branch>. "
            "2) Apply LLM-driven SQL edits per the change plan. "
            "3) Pair every .sql change with its .yml. "
            "4) Add/extend a singular test per new behavior. "
            "5) Run sqlfluff fix if .sqlfluff applies."
        ),
        "preferred_model": resolve_default_llm_model(),
    }


def run(req: ImplementationInput) -> RoleResult:
    branch = _branch_name(req)
    project_dir = Path(req.project_dir).resolve()
    model = resolve_default_llm_model()

    edits: list[FileEdit] = []
    for path in req.validation.code.affected_models:
        edits.append(FileEdit(path=path, summary="Apply requirements-driven change; preserve grain."))
    for path in req.validation.code.affected_macros:
        edits.append(FileEdit(path=path, summary="Update macro to support new requirement."))

    needs_rebuild = any("arr_" in e.path or "stg_arr_categories" in e.path for e in edits)
    impl = ImplementationResult(
        ticket_key=req.requirements.ticket_key,
        branch_name=branch,
        edits=edits,
        needs_snapshot_rebuild=needs_rebuild,
    )
    prompt = _build_llm_prompt(req, branch, model)

    branch_created, branch_msg = _try_create_branch(project_dir, branch)

    return RoleResult(
        role=ROLE,
        status=RoleStatus.NEEDS_INPUT,
        summary=(
            f"Branch '{branch}' {'created' if branch_created else 'NOT created: ' + branch_msg}. "
            f"{len(edits)} files in change plan; LLM coding-agent required to apply "
            f"edits on `{model}`."
        ),
        payload={
            "implementation": impl.as_dict(),
            "prompt": prompt,
            "branch_created": branch_created,
            "branch_message": branch_msg,
            "preferred_model": model,
        },
        pause_reason=f"LLM-driven SQL edits required before test-runner (model: `{model}`)",
        preferred_model=model,
    )


def _branch_name(req: ImplementationInput) -> str:
    key = req.requirements.ticket_key.lower()
    slug = re.sub(r"[^a-z0-9]+", "-", req.requirements.scope_summary.lower()).strip("-")[:40]
    slug = slug or "change"
    return f"{req.branch_prefix}/{key}-{slug}"


def _try_create_branch(project_dir: Path, branch: str) -> tuple[bool, str]:
    check = subprocess.run(
        ["git", "rev-parse", "--verify", branch],
        cwd=str(project_dir), capture_output=True, text=True,
    )
    if check.returncode == 0:
        return False, f"branch already exists at {check.stdout.strip()}"
    create = subprocess.run(
        ["git", "checkout", "-b", branch],
        cwd=str(project_dir), capture_output=True, text=True,
    )
    if create.returncode != 0:
        return False, create.stderr.strip()[:200]
    return True, branch


def _build_llm_prompt(req: ImplementationInput, branch: str, model: str) -> str:
    reqs = req.requirements
    val = req.validation
    lessons_block = _lessons_block("implementer")
    return f"""\
[implementer prompt]
[Preferred model: {model}]

You are the implementer for this ARR analytics-engineering workflow.

Do NOT include agent self-references ("FQC-ARR", "supervisor", "sub-agent",
"Finance ARR Quarter Close", "auto-generated by ...", or similar) in any
code comment, docstring, commit message, PR body, or other output. Lead with
the ticket key and the substance.

{lessons_block}
Branch: {branch} (already checked out)
Ticket: {reqs.ticket_key} - {reqs.scope_summary}

Apply the requirements below as the smallest correct set of edits in this
dbt repo. Follow `.cursor/rules/arr-quarter-close.mdc` guardrails. Pair every
.sql change with its .yml.

In-scope models: {reqs.in_scope_models or '(none flagged; identify before editing)'}
Affected files (code-data-validator scan): {val.code.affected_models}
Affected macros: {val.code.affected_macros}

KPI spec(s):
{chr(10).join('- ' + k.name + ': ' + k.formula for k in reqs.kpis) or '(no KPIs filled - confirm before editing)'}

Proposed changes (from validator):
{chr(10).join('- ' + c for c in val.proposed_changes)}

Risks:
{chr(10).join('- ' + r for r in val.risks)}

Constraints:
- CTE-first; lowercase keywords/identifiers; 140-col line limit; 4-space indent.
- Use ref() / source(); never hardcode tables.
- Preserve grain. Add a unique+not_null test on the PK in the .yml.
- Add or extend a singular test under tests/ for new behavior.

Return a unified diff or write the files directly. Do NOT push the branch -
the pr-author sub-agent does that after the test-runner passes.
"""
