"""Sub-agent 2: requirements-analyzer.

Translates a ``TicketSpec`` into a ``RequirementsSpec`` (KPI-spec framework
from the ``finance-functional-architect`` skill).

This role fundamentally needs an LLM to do the translation well. The module
emits a structured *prompt* that the supervisor (running on Cursor SDK or
SANA) can hand to a model. The module also does cheap structural heuristics
so that even without an LLM, it returns a usable skeleton ``RequirementsSpec``
the user can fill in.
"""

from __future__ import annotations

import re

from agents.arr_quarter_close.contracts import (
    KPISpec,
    RequirementsInput,
    RequirementsSpec,
    RoleResult,
    RoleStatus,
    resolve_default_llm_model,
)
from agents.arr_quarter_close.lessons import (
    format_lessons_for_prompt,
    get_cached_recorder,
)

ROLE = "requirements-analyzer"


def _lessons_block(role: str, max_lessons: int = 8) -> str:
    """Return a Markdown lessons-learned block (or '') for prompt injection."""
    recorder = get_cached_recorder()
    if recorder is None:
        return ""
    return format_lessons_for_prompt(
        recorder.load_for(role, max_lessons=max_lessons),
        heading="Lessons learned from prior runs",
    )


def plan(req: RequirementsInput) -> dict:
    return {
        "role": ROLE,
        "ticket_key": req.ticket.ticket_key,
        "approach": (
            "Apply KPI spec framework (Business Definition / Formula / Grain / "
            "Periodicity / Currency Basis / Filters / Source of Truth / "
            "Validation Rule) to the ticket and its acceptance criteria. "
            "Emit gaps as open questions for the clarifier."
        ),
        "skills": ["finance-functional-architect", "finance-bsa-data-analyst"],
        "preferred_model": resolve_default_llm_model(),
    }


def run(req: RequirementsInput) -> RoleResult:
    skeleton = _heuristic_skeleton(req)
    model = resolve_default_llm_model()
    prompt = _build_llm_prompt(req, model)
    needs_llm = bool(req.ticket.description_text and req.ticket.acceptance_criteria)
    status = RoleStatus.NEEDS_INPUT if needs_llm else RoleStatus.WARN
    summary = (
        f"Heuristic skeleton produced ({len(skeleton.in_scope_models)} candidate models, "
        f"{len(skeleton.questions)} open questions). LLM refinement recommended on "
        f"`{model}`."
    )
    return RoleResult(
        role=ROLE,
        status=status,
        summary=summary,
        payload={
            "requirements": skeleton.as_dict(),
            "prompt": prompt,
            "preferred_model": model,
        },
        pause_reason=(
            f"LLM refinement of RequirementsSpec on `{model}`"
            if needs_llm else None
        ),
        preferred_model=model if needs_llm else None,
    )


_MODEL_HINT_RE = re.compile(
    r"\b(arr_\w+|stg_arr_\w+|stg_em_\w+|wd_\w+_scd2|finance_line_analytics)\b",
    re.IGNORECASE,
)


def _heuristic_skeleton(req: RequirementsInput) -> RequirementsSpec:
    text = "\n".join(
        [req.ticket.summary, req.ticket.description_text]
        + req.ticket.acceptance_criteria
    )
    in_scope = sorted({m.lower() for m in _MODEL_HINT_RE.findall(text)})
    questions: list[str] = []
    if not req.ticket.acceptance_criteria:
        questions.append("No bullet-style acceptance criteria found - confirm AC.")
    if not in_scope:
        questions.append("No obvious dbt model hints in the ticket - which models are affected?")
    if "as_was_date" not in text.lower() and "fiscal" not in text.lower():
        questions.append("Snapshot date / fiscal period scope not explicit - confirm as_was_date.")
    if "currency" not in text.lower() and "usd" not in text.lower():
        questions.append("Currency variant (USD_CURRENT / USD_HIST / USD_ACTUAL) not specified.")
    return RequirementsSpec(
        ticket_key=req.ticket.ticket_key,
        scope_summary=req.ticket.summary,
        in_scope_models=in_scope,
        out_of_scope=[],
        kpis=[],
        questions=questions,
        confidence="low",
    )


def _build_llm_prompt(req: RequirementsInput, model: str) -> str:
    lessons_block = _lessons_block("requirements-analyzer")
    return f"""\
[requirements-analyzer prompt]
[Preferred model: {model}]

You are the requirements-analyzer for this ARR analytics-engineering workflow.
Apply the KPI spec framework from the finance-functional-architect skill to
the ticket below. Return STRICT JSON matching the RequirementsSpec dataclass
(ticket_key, scope_summary, in_scope_models[], out_of_scope[], kpis[], questions[], confidence).

Do NOT include agent self-references ("FQC-ARR", "supervisor", "sub-agent",
"Finance ARR Quarter Close", "auto-generated by ...", or similar) in any
string field. Lead with the ticket key and the substance.

{lessons_block}

For every KPI mentioned or implied, fill: name, business_definition, formula,
grain, periodicity, currency_basis, source_of_truth, validation_rule.
List any gaps as `open_questions` on the KPI or `questions` on the spec.

Ticket {req.ticket.ticket_key}: {req.ticket.summary}
Status: {req.ticket.status}
Labels: {req.ticket.labels}
Components: {req.ticket.components}

Description:
{req.ticket.description_text}

Acceptance criteria (extracted):
{chr(10).join('- ' + ac for ac in req.ticket.acceptance_criteria) or '(none extracted)'}

Return ONLY the JSON object - no surrounding prose.
"""


def empty_kpi() -> KPISpec:  # convenience for downstream callers writing tests
    return KPISpec(
        name="", business_definition="", formula="", grain="", periodicity="",
        currency_basis="", source_of_truth="", validation_rule="",
    )
