"""One-shot seeder for the continuous-learning lessons store.

Run once to populate ``data/lessons/`` with the high-value lessons that
were captured by hand during the early supervisor / debugger / signature
work. After that, the daily-reflection sub-agent keeps the store updated
on its own.

Usage:

    python -m agents.arr_quarter_close.data.seed_lessons

Idempotent: the recorder dedupes by ``(role, lesson)`` hash, so re-running
just bumps ``occurrence_count`` (it does not duplicate rows).
"""

from __future__ import annotations

from pathlib import Path
from typing import Iterable

from agents.arr_quarter_close.lessons import GLOBAL_ROLE, get_recorder


SEED: list[dict] = [
    # ---- Global rules (apply to every role) ------------------------------
    {
        "role": GLOBAL_ROLE,
        "category": "user_preference",
        "lesson": (
            "Never embed agent self-references in user-facing output. "
            "Forbidden phrases: 'FQC-ARR', 'Finance ARR Quarter Close', "
            "'supervisor', 'sub-agent', 'autonomous agent', 'auto-generated by ...', "
            "'Authored by ...', or any trailing signature/footer block in Jira "
            "comments, Slack messages, PR bodies, or generated files. Lead with "
            "the ticket key and the substance. Enforced by "
            ".cursor/rules/no-agent-signatures.mdc."
        ),
        "evidence": (
            "User explicitly asked to strip the 'Posted by FQC-ARR debugger' "
            "footer from a Jira RCA comment and then promoted it to a global rule."
        ),
        "tags": ["jira", "slack", "pr", "signature", "global-rule"],
        "confidence": "high",
        "source_ticket": "EDAEM-3772",
    },
    {
        "role": GLOBAL_ROLE,
        "category": "tooling",
        "lesson": (
            "`slk search` against the enterprise Slack workspace hangs reliably "
            "after a small number of queries. Cap to one search per session, "
            "prefer cached user ids in data/slack_directory.json, and kill any "
            "running `slk` PID before retrying."
        ),
        "evidence": (
            "Multiple `slk search` calls for <person> and <person>'s user ids hung "
            "indefinitely in the EDAEM-3772 session."
        ),
        "tags": ["slack", "slk", "tooling"],
        "confidence": "high",
    },
    {
        "role": GLOBAL_ROLE,
        "category": "tooling",
        "lesson": (
            "Snowflake MCP `snowflake_query` accepts exactly ONE statement per "
            "call. Inline any `SET` constants into the WHERE clause instead of "
            "stacking `SET ...; SET ...; SELECT ...`."
        ),
        "evidence": (
            "Validation query for EDAEM-3772 returned 'Actual statement count 3 "
            "did not match the desired statement count 1' until consolidated."
        ),
        "tags": ["snowflake", "mcp", "tooling"],
        "confidence": "high",
    },

    # ---- Supervisor ------------------------------------------------------
    {
        "role": "supervisor",
        "category": "failure",
        "lesson": (
            "When `--debug-model` is supplied with `--skip jira-intake`, the "
            "debugger cannot run (no TicketSpec). Either auto-include "
            "jira-intake whenever `--debug-model` is set, or pause the debugger "
            "with a clear NEEDS_INPUT message naming the missing dependency."
        ),
        "evidence": (
            "EDAEM-3772 debug attempt returned None silently; the supervisor "
            "needs to surface the missing precondition instead of swallowing it."
        ),
        "tags": ["cli", "debugger", "dag"],
        "confidence": "high",
        "source_ticket": "EDAEM-3772",
    },

    # ---- Debugger --------------------------------------------------------
    {
        "role": "debugger",
        "category": "best_practice",
        "lesson": (
            "When two views compute the 'same' metric at different grains, the "
            "first hypothesis to test is filter-scope mismatch: does each view "
            "apply its lifetime / tenure filter at the SAME grain as its row key? "
            "Confirm by SELECT COUNT(*) ... WHERE filter_a != filter_b at the "
            "join grain before suggesting a fix."
        ),
        "evidence": (
            "EDAEM-3772 root cause: arr_product_customer_retention_dashboard "
            "filtered customer_lifetime at product grain (wd_customer_lifetime_qtr) "
            "while the incremental view filtered at account grain "
            "(customers_total_lifetime_qtr). Excluded long-tenured accounts whose "
            "new products had low product-lifetime (Evisort acquisition, PharmaCord "
            "expansion)."
        ),
        "tags": ["grain-mismatch", "filter-scope", "retention"],
        "confidence": "high",
        "source_ticket": "EDAEM-3772",
    },
    {
        "role": "debugger",
        "category": "best_practice",
        "lesson": (
            "Always validate fix hypotheses through Snowflake MCP before posting "
            "to Jira. The validation query should return the rows the fix would "
            "RECOVER (e.g. 'accounts excluded today that would be included after "
            "the swap'). Quantify the impact (account count, ARR magnitude) in "
            "the RCA comment so the requester can sanity-check it without a re-run."
        ),
        "evidence": (
            "EDAEM-3772 RCA comment cited specific PharmaCord / Evisort accounts "
            "with row counts and product-lifetime values; the requester accepted "
            "the fix on first read."
        ),
        "tags": ["validation", "rca", "jira"],
        "confidence": "high",
        "source_ticket": "EDAEM-3772",
    },

    # ---- Requirements analyzer ------------------------------------------
    {
        "role": "requirements-analyzer",
        "category": "best_practice",
        "lesson": (
            "Spell out the metric grain explicitly in scope_summary (account vs "
            "product vs sku vs ali). Most ARR/NRR/retention bugs reduce to a "
            "grain mismatch between filter and key; flagging the grain upfront "
            "lets the code-data-validator catch it before the implementer wastes "
            "a cycle."
        ),
        "evidence": (
            "EDAEM-3772 would have been caught at requirements review if the "
            "spec had said 'filter on account-level lifetime, not product-level'."
        ),
        "tags": ["grain", "retention", "kpi-spec"],
        "confidence": "medium",
        "source_ticket": "EDAEM-3772",
    },

    # ---- Implementer -----------------------------------------------------
    {
        "role": "implementer",
        "category": "best_practice",
        "lesson": (
            "Every SQL change must ship with its matching test in the same PR: "
            "either a dbt singular test under `tests/` OR a generic schema test "
            "(unique / not_null / accepted_values / dbt_expectations) in the "
            "model's .yml. The test must FAIL on the old code and PASS on the "
            "new code (regression-style)."
        ),
        "evidence": (
            "EDAEM-3772 fix needed a singular test that asserts: no account with "
            "customers_total_lifetime_qtr > 4 is dropped by the dashboard's WHERE "
            "clause, so future grain-scope regressions surface in CI."
        ),
        "tags": ["testing", "regression", "dbt"],
        "confidence": "high",
    },

    # ---- PR author -------------------------------------------------------
    {
        "role": "pr-author",
        "category": "user_preference",
        "lesson": (
            "PR body must NOT contain any agent self-attribution block "
            "(see global rule). Start with the ticket key, scope summary, "
            "what changed (file + before/after), how it was validated "
            "(Snowflake counts, dbt test name), and acceptance criteria check."
        ),
        "evidence": "User feedback from EDAEM-3772 session.",
        "tags": ["pr", "signature", "format"],
        "confidence": "high",
    },

    # ---- CI / CD monitors ------------------------------------------------
    {
        "role": "ci-monitor",
        "category": "best_practice",
        "lesson": (
            "Post `X of N completed` progress updates parsed from the dbt log "
            "step, not just 'queued / running / done'. Use the regex "
            "`(\\d+) of (\\d+) (START|OK|ERROR)` on the dbt run step's log "
            "(via the dbt Cloud API debug-logs endpoint)."
        ),
        "evidence": (
            "User explicitly asked for '6 of 10 completed' style updates in "
            "Slack rather than coarse status pings."
        ),
        "tags": ["dbt-cloud", "slack", "ci"],
        "confidence": "high",
    },
    {
        "role": "cd-monitor",
        "category": "tooling",
        "lesson": (
            "dbt Cloud API calls from Python sometimes hit SSL handshake issues "
            "in this sandbox; shelling out to `curl` is the reliable fallback. "
            "Always have a `curl` path ready when the Python `requests` call "
            "errors out on the privatelink host."
        ),
        "evidence": (
            "watch_pr_ci.py / watch_dbt_run.py both fall back to curl for the "
            "dbt Cloud API after Python SSL errors."
        ),
        "tags": ["dbt-cloud", "curl", "tooling"],
        "confidence": "high",
    },

    # ---- QA handoff ------------------------------------------------------
    {
        "role": "qa-handoff",
        "category": "best_practice",
        "lesson": (
            "The QA handoff comment must carry: (1) PR url and merge sha, "
            "(2) deployed-to-QA confirmation with the dbt Cloud run id, "
            "(3) the 7-col validation matrix or recon table, "
            "(4) explicit @-mention of the requester (resolved via "
            "slack_directory.json). Without (4), the requester sometimes "
            "misses the handoff entirely."
        ),
        "evidence": (
            "User had to manually nudge me to re-ping <person> after the EDAEM-3772 "
            "RCA was posted because no @-mention was included."
        ),
        "tags": ["qa", "handoff", "slack"],
        "confidence": "medium",
    },

    # ---- Clarifier -------------------------------------------------------
    {
        "role": "clarifier",
        "category": "best_practice",
        "lesson": (
            "Default to interactive (terminal) clarification first; only fall "
            "back to a Jira pause-and-post when the operator times out. The "
            "interactive path saves 30-60 minutes of context-switch per ticket. "
            "Honour --no-clarifier-interactive when the run is unattended (CI / "
            "scheduled)."
        ),
        "evidence": (
            "Interactive clarifier shipped in the supervisor; users adopted it "
            "for synchronous sessions immediately."
        ),
        "tags": ["clarifier", "ux"],
        "confidence": "medium",
    },
]


def seed(project_dir: Path = Path(".")) -> int:
    recorder = get_recorder(project_dir)
    added_or_bumped = 0
    for item in SEED:
        if recorder.record(**item) is not None:
            added_or_bumped += 1
    print(f"Seeded {added_or_bumped} lessons (existing entries had occurrence_count bumped).")
    return added_or_bumped


if __name__ == "__main__":
    import sys
    sys.exit(0 if seed(Path(".")) >= 0 else 1)
